user_list:
  path: /api/users
  controller: App\Controller\UserController:indexAction
  methods: [GET]

user_create:
  path: /api/user/new
  controller: App\Controller\UserController:createAction
  methods: [ POST ]

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }