user_list:
  path: /userList
  controller: App\Controller\UserController:indexAction
  methods: [GET]

user_create:
  path: /userCreate
  controller: App\Controller\UserController:createAction
  methods: [ POST ]